// 将Excel列数据保存为company_list.js
const EXCEL_COMPANIES = [
  "(A Barcoding, Inc. Company)",
  "(Barcode Buyback)",
  "(Barcode Repair)",
  "(Barcode Trade)",
  "(Barcode-house) DecisionPoint Technologies",
  "(BayInfoTech Corp)",
  "(Best4Systems)",
  "(DMS Technologies Inc)",
  "(Hardware Direct)",
  "(JPT barcode)",
  "(Lean Supply Solutions, Emerge IP)",
  "(MMX Communications)",
  "(MRP, MRP - A ServIT Company)",
  "(PICS Telecom International Asia Ltd. )",
  "(PICS Telecom International Ltd. )",
  "(TRG)",
  "(Techworks)",
  "(Tier1 Asset A/S) Tellusrem)",
  "(Trade Develepment Strategies Inc.)",
  "(aka IB REMARKETING, Technogroup IT-Service Sp. z o.o )",
  ", ServerMark )",
  "1st Tier Technology",
  "=Amerinode Brazil /Amerinode Ecuador/Amerinode South America",
  "A-tech network",
  "A2C Services Ltd/ Circular Computing",
  "AJ Networx",
  "Advance Services & Solutions Ltd",
  "Advance Vendor Access",
  "Advanced Computer Systems LLC(ACS)",
  "Advanced Computer Trading (actsl.com)",
  "Advanced Technologies International LLC",
  "AlfaNet S.A. (AlfaNet SYSTIMATA) ALFANET SISTIMATA PLIROFORIKIS S.A",
  "Alpha-Dox（Alpha-Dox B.V.）",
  "Alta Technologies, Inc.",
  "Amerinode=AMERINODE VZ, C.A =AMERINODE DE MEXICO S.A. DE C.V.",
  "Andrej Lamovsek",
  "Anlauf Hardware GmbH",
  "Apronet - IT Distribution (APRONET UNIPESSOAL LDA)",
  "Arbitech, LLC(BecTech Global)",
  "Arcas Technology Inc",
  "Arzotec ApS",
  "Astringo Commodities Ltd (Rugged.tech)",
  "Atoutek SAS",
  "BE NETWORKS",
  "BT Systems Inc",
  "BUILD369 doo",
  "Backslash Vertriebs GmbH",
  "Ballet jean marc",
  "Barcode Supply",
  "BayInfoNet Corp",
  "Bell IT GmbH (Bell IT Inc.)",
  "Billigteknik Sweden AB",
  "Bitboard OÜ (LLC)",
  "Bitcare - Tecnologias de Informacao, SA",
  "BrainBridge Outsourcing Services Pvt Ltd",
  "Bravo Communication, Global net source(GNS)/Singular Grape Inc",
  "BrokenMedia LLC (Breckline Technologies)",
  "Brugtecomputere.dk (Ecommunication A/S)",
  "BudgetTrading",
  "C2 Digital Solutions Ltd",
  "CARRIER SERVICES GROUP （CSG）",
  "CBA Computer Broker AG",
  "COMPOSITE NETWORK",
  "CUADRANT ( Netmode, NETGenetics, Platform Management LLC, Accela Networks , Volantra Networks)",
  "Caique goncalves",
  "Carlex Ltd",
  "Carlton Technologies, Levata (Barcodes, Inc, BarcodesInc)",
  "Carritech Limited (Carritech Telecomunicaciones S.L.U)",
  "Circular IT",
  "Cobra Tech Solutions LLC",
  "Codelogic",
  "Codeo (Codeo Iberia)",
  "Codinfos",
  "ComSources, LLC",
  "Combro Technology Limited",
  "Comptest Polska Sp z o. o. (COMPTEST GROUP SP Z O.O.)",
  "Computer-wereld",
  "Comstex GmbH & Co. KG",
  "Connect IT (Connect IT B.V.) （Info . Connect IT）",
  "Connectzone /Technacable",
  "Continental Computers",
  "Control House International",
  "Cyberpulse Computing LTD",
  "Cybertrading GmbH (IT Market, IT-Market)",
  "Cykero",
  "Cykero GMBH",
  "Cykero SAS",
  "Cypress Technology, Inc(J+J Nationwide enterprises)",
  "D&B Distributors Ltd",
  "D&S Communications, Inc.",
  "DMS Technology, Inc.",
  "Dan-Mar Components, Inc.(Prime Electronic Components)",
  "Dansk Computer Center A/S (DCC)",
  "Data Networks International (Data Networks Int’l)",
  "Datamarked Aps（ITFIX Mariusz Fiertek）",
  "Datamax Services Inc.",
  "Datamax System Solutions",
  "Dealstunter",
  "DiGiworks Co., Ltd(CharonTech Co., Ltd) KERBEROS CO.",
  "Digoo IT Distribution",
  "Direct Hardware Supply (DHS)",
  "Diversitec",
  "Docwizz SRL",
  "EONETIX Information Technology",
  "ESI Technologies Inc",
  "ESphere Network GmbH",
  "ETB Technologies Ltd",
  "Easy Hardware Trading",
  "Ecodair ea Paca",
  "Ecoele UG",
  "Econocom Factory",
  "Ecoportatil.es (PORTATILECO ESPAÑA S.L)",
  "Enterasource LLC",
  "Enterprise Data Resources, Inc(EDR / usedbarcode / edrbarcode / barcode-arena)",
  "Estunt BV",
  "Euro IT Solution LTD (Tier1 Data Systems)",
  "European Network Services SARL (ENS)",
  "Evernex",
  "ExcessIT Middle East Electronics Trading L.L.C",
  "FEATURECOM INC.",
  "FLEXIT B.V. (Xeptor B.V. , Flex IT Distribution, Infotheek Groep NV, Infotheek Holding B.V.)",
  "FORSERVER ( Universal Technology & Logistics INC",
  "FTNC Ltd (Forward Thinking Network Consultancy Ltd)",
  "Fala Limited",
  "Feda Trading BV",
  "Flagship Technologies Inc.",
  "Flux IT Hardware Ltd",
  "For Your Workplace LTD",
  "Four IT Group(D-TWO B.V.)",
  "Four Nordic",
  "Foxway A/S",
  "Foxway Distribution",
  "Foxway OU",
  "Foxway UK",
  "Frogtech",
  "G&S Communications and Technical Services",
  "G5 Network（G5 Network Group）",
  "GRUPO DIGALCO SL",
  "GSD Remarketing GmbH & Co. KG (gsd.eu)",
  "Get IT New Inc",
  "Ghekko Limited (Ghekko Networks Inc. , A1 Teletronics, Inc.)",
  "Global Computer Sales",
  "Global United LLP",
  "Glocean INC (Synotex INC, PAX Solutions)",
  "Go Communications Systems",
  "Good PC OU（Good PC OÜ，Wise Europe S.A，Good Choice）",
  "Great Windmill c/o Procurri",
  "Greyhound Networks Ltd",
  "Group24 AG",
  "HCO Group Limited (Re-Macs)",
  "Hardware You & Cloud",
  "Hardware You SLU",
  "Hillside Electronics Corporation",
  "I mac and more",
  "ICS Europe Ltd (INTEGRATED COMPONENT SOURCE EU LTD)",
  "IMN",
  "IP Supply Pty Ltd",
  "IT Gigant ( RCW) (Retail Computer Warehouse)",
  "IT WEST STORE （IT WEST STORE LLC-FZ）",
  "IT-Planet GmbH",
  "IT4Trade",
  "Illinois Wholesale Cash Register (IW Technologies)",
  "Impact Computers",
  "Index Computer Remarketing",
  "Infocus ID Ltd",
  "Inforsight Ltd Inforsight Limited",
  "Infos",
  "Inrego AB (Inrego Global AB)",
  "Integrity Global Solutions (IGS)",
  "InterNative Supply",
  "Interbolt.eu Kft",
  "Interbyte Pty Ltd",
  "Interlink Computer Shop (Interlink Group srl)",
  "Iris Conex Ltd",
  "JANS-it",
  "JP Computer Trading",
  "Jerry Howard",
  "KONSER OHG (notebookgalerie.de)",
  "KT-Trading OY",
  "Kimbrer Computer ApS (Renewtech)",
  "LM Eco Production",
  "LSI Technology Remarketing (LSI) (EZZELL ENTERPRISE, INC)",
  "Lorimax 2000 Impex srl (SC LORIMAX 2000 IMPEX SRL)",
  "M&M",
  "MAG Traders Ltd",
  "MAS Integrated Systems(MAS)Ceremony LTD",
  "MCR-Austria / Mobile Computer Repair",
  "MF Communications Limited",
  "MIDRANGE REPAIR & PARTS",
  "MS Development",
  "MTJ Electronics",
  "MTS IT Systems",
  "MULTIPLE NETWORKS LTD",
  "Macondo Networks",
  "Macrefresh Ltd",
  "Maker IT",
  "Maraelite Kft",
  "Marseus Computer Kft",
  "Master for computer (Luxury Store)",
  "Matrizmultipla - Unipessoal LDA",
  "Max ICT B.V.",
  "Media & Communications Ltd",
  "Mekhrob NAVRUZOV",
  "Memtech sp. z o.o. sp. kom.",
  "Menke IT GmbH",
  "MetrolineDirect (Metroline Inc, Phone Installers)",
  "Micro Solution Web LCC",
  "Micropeer Solutions",
  "Mileservices",
  "MinutioConsultingGmbH (Minutio Consulting GmbH)",
  "Missdata Di Romano Scilla （MISSDATA SRLS）",
  "Mosaic Technology Corporation",
  "My IT Street (MIS)",
  "NAS IT Solutions Ltd",
  "NCOM SRL",
  "NCS Global Services LLC/NCS West",
  "NKS Group Sp. z o. o.",
  "NTAST",
  "Nanosoft Corporation Limited",
  "Neo Data Technologies LLC",
  "Network Craze Technologies",
  "Network ISE Digital Technologies LTD (NETWORKISE CLOUD TECHNOLOGIES L.L.C)",
  "NewAge Technology Solutions, LLC",
  "NexGen Technology LLC (Hardware Storm)",
  "Nexus Node Systems LTD",
  "Nidam Communication = Chip PC Inc.",
  "Nomadiel",
  "Northland Systems",
  "Notebook-Pro NPH GmbH",
  "Notebookservice SRL (keyboardprint, AKCENTA CZ A.S. )",
  "On Queue Computer Inc",
  "Open Market Trading, LLC",
  "Optimum Routing Machine Systems FZCO（ORM Systems）",
  "Oredax",
  "Origin Micro, Inc",
  "Otisco valley telcom",
  "OutletClick.Com (Insis d.o.o.)",
  "Overseas Technology Center Pte LTd",
  "P3 Systems",
  "PBXports Ltd",
  "PC Renewed Ltd",
  "PC warehouse",
  "PCM Leasing Corp",
  "PDAserwis (PDAgroup , 24barcode)",
  "PICS Telecom",
  "POS Solutions s.r.o.",
  "PT Refurb Unipessoal Lda / RFI UNIP LDA",
  "PULSEINFORMATICA",
  "Paragon Communications Inc(PARAGON, NTS DIRECT) Telesource Services, Inc",
  "Paxel Technologies",
  "Pecunia24",
  "Pexbo (RED AND WHITE NETWORK LLC) Copy Solutions SRL",
  "Phoenix Tech s.r.l. (Hi-Tech Outlet)",
  "Pine Group BV",
  "Pine Projects BV",
  "Pine Services BV",
  "Pine Supplies BV",
  "PowerTech Inc",
  "Powerful system",
  "Preyveng Trading Ltd",
  "Procurri",
  "Procurri Asia Pacific, Procurri Europe Lifecycle Services,",
  "Procurri Europe Ltd (Procurri Europe Parts Sales),",
  "Procurri GmbH,",
  "Procurri Malaysia Sdn,",
  "Procurri Singapore Pte Ltd,",
  "Procurri USA,",
  "Propersearch Ltd",
  "Prospect Communications, Inc. (Prospect computer)",
  "Pure IT Recycling",
  "Q Products BV",
  "Quazo Systems",
  "RAA IT Solution",
  "RAA TECHNOLOGY SOLUTIONS LTD",
  "RADAN TRADE",
  "RECYCLY.TECH LTD",
  "RED EAGLE IT Distribution GmbH",
  "REVOLVING NETWORKS",
  "RL Networks B.V. (Maxicom IT Distribution B.V.) CITg Netherlands B.V.",
  "RQ Communications (Retrotel, Inc)",
  "RS ITL Verwaltungs GmbH",
  "ReCon-IT GmbH",
  "Redsis Corp",
  "Refurb-UK",
  "Renew-IT Solutions (GVS Consulting) (GVS Consulting COMMV)",
  "Resource Point of Sale",
  "Retail Tech Inc",
  "ReuseIT Sweden AB",
  "Revo Distribution Limited",
  "Rhino technology",
  "RuA Bademli GbR",
  "SBS Trading LTD",
  "SCSISTUFF, LLC",
  "SPC - Sales & Purchasing Consultancy",
  "SPC International Ltd (Rico Logistics Ltd) (TVS Supply Chain Solutions, TVSSCS)",
  "SPLUS TECHNOLOGIES LLC",
  "SabrePC.com/Exxact Corporation",
  "Sahar gul computer Tr llc",
  "ScanFocus",
  "ScandicTech AS",
  "Scottish Data Systems",
  "Sell Phone System (Clarion Communication Systems Ltd)",
  "Serverfi Ltd",
  "Shields Environmental Ltd",
  "Shop4Tele Inc (Techzone Direct)",
  "Simpatico Network srl",
  "Smart Dragon SL",
  "Somet Integration Ltd",
  "Sotel Systems",
  "South Supply TN",
  "Stack Systems KFT(Stack Systems Trade FZ LLC)",
  "Sterling Mobile Services, Inc",
  "Sterry Telecom",
  "Strada Networks, LLC (DCS Global B.V. , Data Center Solutions)",
  "SunCoast Communication",
  "Superior Telecom,LLC",
  "Surplus Computer Spares (SCS)",
  "T.I Digital Solution LTD",
  "TDS",
  "TDW (Technology Distribution Worldwide LLC）",
  "THORPETO INC",
  "TKO Electronics, Inc. (ExpressPoint Technology)",
  "TSP SYSTEM Co.,Ltd",
  "TVDL Computers",
  "TXC Technologies LLC",
  "TXO Systems",
  "Taldor Group (Taldor computer systems (1986) Ltd)",
  "Tawakkal Infotech LLC (LinkServe) LINK SUPPORT FOR INDUSTRIAL SERVICES EST (Linkserve)",
  "Tazabitz Computer Consulting Inc",
  "TecBox",
  "Tech Network Supply LLC(Yellow Networks LLC)",
  "Technimax s.r.o.",
  "Technimove Recycles",
  "Technology Recovery Group/TRG Global",
  "Technoverse Business Solutions",
  "Techsource / Techsource Global (TSGlobal.io)",
  "Tecnoban Inc",
  "Tekeurope UK Ltd",
  "Teksavers (Singapore)",
  "Teksavers Inc",
  "Tekserve, Inc",
  "TelQuest International",
  "Telecom Easy Scandinavia AB",
  "Telecom Supplier Deutschland GmbH",
  "Telecoms Traders Ltd",
  "Telefone Resources (UK) Ltd",
  "Tellus Remarketing ApS",
  "Thats IT",
  "The Best Part, Inc.",
  "Thinkgreen SARL （SARL THINKGREEN - INFO26200）",
  "Today Tech",
  "Toga Informática",
  "Tradenet Technology",
  "Trio Supply Chain Solutions, LLC",
  "True Technologies LLC",
  "Versatile Mobile Systems",
  "Vibrant Technologies, Inc.",
  "Viking Computer Parts, Inc",
  "Vladimir Chumakov / Hells Dells Chumakov / Aranovsky GbR",
  "Vodanet Systems LLC (Wisewired) Euronet Systems GmbH",
  "Vooruit",
  "WDIXITAL SPAIN, SLU",
  "Washburn Computer Group",
  "WestWorld Telecom Corporation",
  "Z3-IT, Onken IHB UG(Stahlmann & Sachs GmbH) BM Networks, Blue Mountain Networks LLC (Platinum Networks, Inc.)  Telecom Discount B.V",
  "Zayntek (Fornida)",
  "aam muharam",
  "cheolhwa lee （joosung）",
  "ermenegildo arrivillaga",
  "fortune associates(Shakun Associates Inc， Shakun Associates Private Limited)",
  "furbify s.r.o.",
  "inComputer s.r.o",
  "okpos chile spa (Comercializadora e importadora Renmar limitada)",
  "preiswerte-IT.de GmbH",
  "reflex.sys",
  "refublic",
  "sofigroupe (Econocom SA, SMAAART, Jiliti)",
  "tacladders it",
  "technocycle GmbH",
  "telecomhunter",
  "telecomsupplier",
  "wizzardwerks",
  "zekers",

  //有误的数据
  "Rhino Technology Group, Inc",
  "MF Communications UK Ltd",
  "TEKEUROPE UK",
  "Renewtech DK fka. Kimbrer Computer ApS",
  
  //新增干净数据
  "IT Product Supply LTD",
  "Bizcom Europe Sp. z o.o.",
  "Elevate Networks",
  "SKTes France, SKtes Spain",
  "Computer Data Source",
  "Mobilos Single Member P.C. | VMS",
  "Jet Computer",

  //新增别名数据 干净数据里的
  "VOTERONIX LTD",

  //没找到的公司
  "Andeltech Electronics, GIGAHARDWARE",

  //中国公司
  "Acorn Tech Service Limited",
  "Quiksol International HK PTE limiteds  ",
  "Highsource Technology Co.Ltd",
  "CENTURY FUGUANG CO., LTD.",
  "Grandtec Industrial (Hongkong) Co., Ltd",
  "Shengyue Technology Co., Ltd",
  "Convey Telecom Limited",
  "Top IT Service Limited,fka Uniworld",
  "DECHO Network Technology LTD",
  "Joy Online Network Limited",
  "Coopak Networks",

  //被拉黑
  "Memory Clearance",
];
