// 将Excel列数据保存为company_list.js
const EXCEL_COMPANIES = [
  "1st Tier Technology",
  "A-tech network",
  "A.B. Distributing, Inc (B3E LLC, Sachem, LLC)",
  "A2C Services Ltd/ Circular Computing",
  "ADCbit B.V.",
  "ADE-Vertriebs GmbH",
  "AJ Networx",
  "Advance Services & Solutions Ltd",
  "Advance Vendor Access",
  "Advanced Computer Trading (actsl.com)",
  "Advanced Technologies International LLC",
  "AirWay Technologies, INC",
  "AlfaNet S.A. (AlfaNet SYSTIMATA) ALFANET SISTIMATA PLIROFORIKIS S.A",
  "All Birotic Devices",
  "Alpha-Dox（Alpha-Dox B.V.）",
  "Alta Technologies, Inc.",
  "America Tecnologia",
  "Amerinode=AMERINODE VZ, C.A =AMERINODE DE MEXICO S.A. DE C.V. 
=Amerinode Brazil /Amerinode Ecuador/Amerinode South America",
  "Ameta Computer ApS",
  "Andrej Lamovsek",
  "Anlauf Hardware GmbH",
  "Apronet - IT Distribution (APRONET UNIPESSOAL LDA)",
  "Arcas Technology Inc",
  "Arzotec ApS",
  "Astringo Commodities Ltd (Rugged.tech)",
  "Astrocom Systems((VCF) )",
  "AtlasPhones.com
(Atlas Systems Inc)
(TelecomRecycle)",
  "Atoutek SAS",
  "BE NETWORKS",
  "BT Systems Inc",
  "BUILD369 doo",
  "Backslash Vertriebs GmbH",
  "Ballet jean marc",
  "Barcode Supply
(Barcode Buyback)",
  "BayInfoNet Corp
(BayInfoTech Corp)",
  "Bell IT GmbH (Bell IT Inc.)",
  "Billigteknik Sweden AB",
  "Bitcare - Tecnologias de Informacao, SA",
  "Blue Point Voice and Data",
  "BrainBridge Outsourcing Services Pvt Ltd",
  "Bravo Communication, Global net source(GNS)/Singular Grape Inc",
  "BrokenMedia LLC (Breckline Technologies)",
  "Brugtecomputere.dk (Ecommunication A/S)",
  "BudgetTrading",
  "C2 Digital Solutions Ltd",
  "CARRIER SERVICES GROUP （CSG）",
  "CBA Computer Broker AG",
  "COMPOSITE NETWORK",
  "CUADRANT ( Netmode, NETGenetics, Platform Management LLC, Accela Networks , Volantra Networks)",
  "Caique goncalves",
  "Carlex Ltd",
  "Carlton Technologies, Levata (Barcodes, Inc, BarcodesInc)",
  "Carritech Limited (Carritech Telecomunicaciones S.L.U)",
  "Circular IT",
  "Cobra Tech Solutions LLC",
  "Codelogic",
  "Codeo (Codeo Iberia)",
  "Codinfos",
  "ComSources, LLC",
  "Combro Technology Limited",
  "Communications & Data, Inc（C&D Associates, Inc./C&D Communications,Inc）",
  "Comptest Polska Sp z o. o. (COMPTEST GROUP SP Z O.O.)",
  "Computer-wereld",
  "Connect IT (Connect IT B.V.) （Info . Connect IT）",
  "Connectzone /Technacable",
  "Continental Computers",
  "Control House International",
  "Cyberpulse Computing LTD",
  "Cybertrading GmbH (IT Market, IT-Market)",
  "Cykero
Cykero GMBH
Cykero SAS",
  "Cypress Technology, Inc(J+J Nationwide enterprises)",
  "D&B Distributors Ltd",
  "D&S Communications, Inc.",
  "DMS Technology, Inc.
(DMS Technologies Inc)",
  "DSM Distribution",
  "Dan-Mar Components, Inc.(Prime Electronic Components)",
  "Data Capture Solutions
(Legacy Technology Services)",
  "Data Networks International (Data Networks Int’l)",
  "Datamarked Aps（ITFIX Mariusz Fiertek）",
  "Datamax System Solutions
Datamax Services Inc.",
  "Dealstunter",
  "DiGiworks Co., Ltd(CharonTech Co., Ltd) KERBEROS CO.",
  "Digoo IT Distribution",
  "Direct Hardware Supply (DHS)",
  "Diversitec",
  "EONETIX Information Technology",
  "ESI Technologies Inc",
  "ESphere Network GmbH",
  "ETB Technologies Ltd",
  "Easy Hardware Trading",
  "Ecodair ea Paca",
  "Ecoele UG",
  "Econocom Factory 
sofigroupe (Econocom SA, SMAAART, Jiliti)",
  "Ecoportatil.es (PORTATILECO ESPAÑA S.L)",
  "Enterasource LLC",
  "Enterprise Data Resources, Inc(EDR / usedbarcode / edrbarcode / barcode-arena)",
  "Estunt BV",
  "Euro IT Solution LTD (Tier1 Data Systems)",
  "European Network Services SARL (ENS)",
  "Evernex
(aka IB REMARKETING, Technogroup IT-Service Sp. z o.o )",
  "FEATURECOM INC.
(Lean Supply Solutions, Emerge IP)",
  "FLEXIT B.V. (Xeptor B.V. , Flex IT Distribution, Infotheek Groep NV, Infotheek Holding B.V.)",
  "FORSERVER ( Universal Technology & Logistics INC
, ServerMark )",
  "FTNC Ltd (Forward Thinking Network Consultancy Ltd)",
  "Fala Limited
(Barcode Trade)",
  "Feda Trading BV",
  "Flagship Technologies Inc.",
  "Flux IT Hardware Ltd",
  "For Your Workplace LTD 
Pine Supplies BV
Pine Projects BV
Pine Group BV
Pine Services BV
Telecom Supplier Deutschland GmbH
telecomhunter
telecomsupplier",
  "Four IT Group(D-TWO B.V.)",
  "Four Nordic",
  "Foxway OU
Foxway UK
Foxway A/S
Foxway Distribution
Dansk Computer Center A/S (DCC)
ExcessIT Middle East Electronics Trading L.L.C",
  "Frogtech",
  "G5 Network（G5 Network Group）",
  "GRUPO DIGALCO SL",
  "GSD Remarketing GmbH & Co. KG (gsd.eu)
RS ITL Verwaltungs GmbH",
  "Get IT New Inc",
  "Ghekko Limited (Ghekko Networks Inc. , A1 Teletronics, Inc.)",
  "Global Computer Sales",
  "Global United LLP",
  "Glocean INC (Synotex INC, PAX Solutions)",
  "Go Communications Systems",
  "Good PC OU（Good PC OÜ，Wise Europe S.A，Good Choice）",
  "Greyhound Networks Ltd",
  "Group24 AG",
  "HCO Group Limited (Re-Macs)",
  "Hardware You SLU
Hardware You & Cloud",
  "Hillside Electronics Corporation",
  "I mac and more",
  "ICS Europe Ltd (INTEGRATED COMPONENT SOURCE EU LTD)",
  "IMN",
  "IP Supply Pty Ltd",
  "IT Gigant ( RCW) (Retail Computer Warehouse)",
  "IT WEST STORE （IT WEST STORE LLC-FZ）",
  "IT-Planet GmbH",
  "IT4Trade",
  "Illinois Wholesale Cash Register (IW Technologies)",
  "Impact Computers",
  "Index Computer Remarketing",
  "Inforsight Ltd Inforsight Limited",
  "Infos",
  "Inrego AB (Inrego Global AB)",
  "Integrity Global Solutions (IGS)",
  "InterNative Supply",
  "Interbolt.eu Kft",
  "Interbyte Pty Ltd",
  "Interlink Computer Shop (Interlink Group srl)",
  "Iris Conex Ltd",
  "JP Computer Trading",
  "Jerry Howard",
  "KONSER OHG (notebookgalerie.de)",
  "Kimbrer Computer ApS (Renewtech)",
  "LM Eco Production",
  "LSI Technology Remarketing (LSI) (EZZELL ENTERPRISE, INC)",
  "Lorimax 2000 Impex srl (SC LORIMAX 2000 IMPEX SRL)",
  "M&M",
  "MAG Traders Ltd",
  "MAS Integrated Systems(MAS)Ceremony LTD",
  "MCR-Austria / Mobile Computer Repair",
  "MF Communications Limited",
  "MIDRANGE REPAIR & PARTS 
(MRP, MRP - A ServIT Company)",
  "MS Development
(Hardware Direct)",
  "MTJ Electronics",
  "MTS IT Systems",
  "MULTIPLE NETWORKS LTD",
  "Macondo Networks",
  "Macrefresh Ltd",
  "Maker IT",
  "Maraelite Kft",
  "Marseus Computer Kft",
  "Master for computer (Luxury Store)",
  "Max ICT B.V.",
  "Media & Communications Ltd
(Best4Systems)",
  "Mekhrob NAVRUZOV",
  "Memtech sp. z o.o. sp. kom.",
  "Menke IT GmbH",
  "MetrolineDirect (Metroline Inc, Phone Installers)",
  "Micro Solution Web LCC",
  "Micropeer Solutions",
  "Mileservices",
  "MinutioConsultingGmbH (Minutio Consulting GmbH)",
  "Missdata Di Romano Scilla （MISSDATA SRLS）",
  "Mosaic Technology Corporation",
  "My IT Street (MIS)",
  "NAS IT Solutions Ltd",
  "NCOM SRL",
  "NCS Global Services LLC/NCS West",
  "NKS Group Sp. z o. o.",
  "Nanosoft Corporation Limited",
  "Neo Data Technologies LLC",
  "Network Craze Technologies",
  "Network ISE Digital Technologies LTD (NETWORKISE CLOUD TECHNOLOGIES L.L.C)",
  "NewAge Technology Solutions, LLC",
  "NexGen Technology LLC (Hardware Storm)",
  "Nexus Node Systems LTD",
  "Nidam Communication = Chip PC Inc.",
  "Nomadiel",
  "Northland Systems",
  "Notebookservice SRL (keyboardprint, AKCENTA CZ A.S. )",
  "On Queue Computer Inc",
  "Open Market Trading, LLC",
  "Optimum Routing Machine Systems FZCO（ORM Systems）",
  "Oredax",
  "Origin Micro, Inc",
  "Otisco valley telcom",
  "OutletClick.Com (Insis d.o.o.)",
  "P3 Systems",
  "PBXports Ltd",
  "PC Renewed Ltd",
  "PC warehouse",
  "PCM Leasing Corp",
  "PDAserwis (PDAgroup , 24barcode)",
  "PICS Telecom
(PICS Telecom International Ltd. )
(PICS Telecom International Asia Ltd. )",
  "POS Solutions s.r.o.",
  "PT Refurb Unipessoal Lda / RFI UNIP LDA",
  "PULSEINFORMATICA",
  "Paragon Communications Inc(PARAGON, NTS DIRECT) Telesource Services, Inc",
  "Paxel Technologies",
  "Pecunia24",
  "Pexbo (RED AND WHITE NETWORK LLC) Copy Solutions SRL",
  "Phoenix Tech s.r.l. (Hi-Tech Outlet)",
  "PowerTech Inc",
  "Powerful system",
  "Preyveng Trading Ltd",
  "Procurri
Procurri Europe Ltd (Procurri Europe Parts Sales),
Procurri Asia Pacific, Procurri Europe Lifecycle Services, 
Procurri USA, 
Procurri GmbH, 
Procurri Singapore Pte Ltd,
Procurri Malaysia Sdn,
Great Windmill c/o Procurri",
  "Propersearch Ltd",
  "Prospect Communications, Inc. (Prospect computer)",
  "Pure IT Recycling",
  "Q Products BV",
  "Quazo Systems",
  "RAA TECHNOLOGY SOLUTIONS LTD 
RAA IT Solution",
  "RADAN TRADE",
  "RECYCLY.TECH LTD",
  "RED EAGLE IT Distribution GmbH",
  "REVOLVING NETWORKS",
  "RL Networks B.V. (Maxicom IT Distribution B.V.) CITg Netherlands B.V.",
  "RQ Communications (Retrotel, Inc)",
  "Re-certify",
  "ReCon-IT GmbH",
  "Redsis Corp",
  "Resource Point of Sale",
  "Retail Tech Inc",
  "ReuseIT Sweden AB",
  "Rhino technology",
  "RuA Bademli GbR",
  "SBS Trading LTD",
  "SCSISTUFF, LLC",
  "SPC - Sales & Purchasing Consultancy",
  "SPC International Ltd (Rico Logistics Ltd) (TVS Supply Chain Solutions, TVSSCS)",
  "SPLUS TECHNOLOGIES LLC",
  "SabrePC.com/Exxact Corporation",
  "Sahar gul computer Tr llc",
  "ScanFocus",
  "ScandicTech AS",
  "Scottish Data Systems",
  "Seamless IT",
  "Sell Phone System (Clarion Communication Systems Ltd)",
  "Serverfi Ltd",
  "Shields Environmental Ltd",
  "Shop4Tele Inc (Techzone Direct)",
  "Simpatico Network srl",
  "Smart Dragon SL",
  "Somet Integration Ltd",
  "Sotel Systems",
  "South Supply TN",
  "Stack Systems KFT(Stack Systems Trade FZ LLC)",
  "Sterry Telecom",
  "Strada Networks, LLC (DCS Global B.V. , Data Center Solutions)",
  "SunCoast Communication",
  "Superior Telecom,LLC",
  "Surplus Computer Spares (SCS)",
  "T.I Digital Solution LTD",
  "TDS 
(Trade Develepment Strategies Inc.)",
  "TDW (Technology Distribution Worldwide LLC）",
  "THORPETO INC",
  "TKO Electronics, Inc. (ExpressPoint Technology)",
  "TSP SYSTEM Co.,Ltd",
  "TVDL Computers",
  "TXC Technologies LLC",
  "TXO Systems
(MMX Communications)",
  "Taldor Group (Taldor computer systems (1986) Ltd)",
  "Tawakkal Infotech LLC (LinkServe) LINK SUPPORT FOR INDUSTRIAL SERVICES EST (Linkserve)",
  "Tazabitz Computer Consulting Inc",
  "TecBox",
  "Tech Network Supply LLC(Yellow Networks LLC)",
  "Technimax s.r.o.",
  "Technimove Recycles",
  "Technology Recovery Group/TRG Global
 (TRG)
(Barcode Repair)",
  "Technoverse Business Solutions",
  "Techsource / Techsource Global (TSGlobal.io)",
  "Tecnoban Inc",
  "Teksavers Inc
Teksavers (Singapore)",
  "Tekserve, Inc",
  "TelQuest International",
  "Telecom Easy Scandinavia AB",
  "Telecoms Traders Ltd",
  "Telefone Resources (UK) Ltd",
  "Tellus Remarketing ApS
(Tier1 Asset A/S) Tellusrem)",
  "Thats IT",
  "The Best Part, Inc.",
  "Thinkgreen SARL （SARL THINKGREEN - INFO26200）",
  "Today Tech",
  "Toga Informática",
  "Tradenet Technology",
  "Trio Supply Chain Solutions, LLC",
  "True Technologies LLC",
  "Versatile Mobile Systems
(JPT barcode)
(A Barcoding, Inc. Company)
(Barcode-house) DecisionPoint Technologies",
  "Vibrant Technologies, Inc.
(Techworks)",
  "Viking Computer Parts, Inc",
  "Vladimir Chumakov / Hells Dells Chumakov / Aranovsky GbR",
  "Vodanet Systems LLC (Wisewired) Euronet Systems GmbH",
  "WDIXITAL SPAIN, SLU",
  "Washburn Computer Group",
  "WestWorld Telecom Corporation",
  "Z3-IT, Onken IHB UG(Stahlmann & Sachs GmbH) BM Networks, Blue Mountain Networks LLC (Platinum Networks, Inc.)  Telecom Discount B.V",
  "Zayntek (Fornida)",
  "aam muharam",
  "cheolhwa lee （joosung）",
  "ermenegildo arrivillaga",
  "fortune associates(Shakun Associates Inc， Shakun Associates Private Limited)",
  "furbify s.r.o.",
  "inComputer s.r.o",
  "okpos chile spa (Comercializadora e importadora Renmar limitada)",
  "preiswerte-IT.de GmbH",
  "reflex.sys",
  "refublic",
  "tacladders it",
  "technocycle GmbH",
  "wizzardwerks",
  "zekers",
];