// 将Excel列数据保存为company_list.js
const EXCEL_COMPANIES = [
/// 李彩霞
  "AtlasPhones.com (Atlas Systems Inc) (TelecomRecycle)",
  "Dan-Mar Components, Inc.(Prime Electronic Components)",
  "Enterprise Data Resources, Inc(EDR / usedbarcode / edrbarcode / barcode-arena)",
  "Nomadiel",
  "Prospect Communications, Inc. (Prospect computer)",
  "Alta Technologies, Inc.",
  "BrokenMedia LLC (Breckline Technologies)",
  "PowerTech Inc",
  "Easy Hardware Trading",
  "Enterasource LLC",
/// 刘敏燕
  "America Tecnologia",
  "fortune associates(Shakun Associates Inc， Shakun Associates Private Limited)",
  "Infos",
  "MIDRANGE REPAIR & PARTS  (MRP, MRP - A ServIT Company)",
  "Redsis Corp",
  "Superior Telecom,LLC",
  "TDS  (Trade Develepment Strategies Inc.)",
  "Tekserve, Inc",
  "Versatile Mobile Systems (JPT barcode) (A Barcoding, Inc. Company) (Barcode-house) DecisionPoint Technologies",
  "Viking Computer Parts, Inc",
  "Amerinode=AMERINODE VZ, C.A =AMERINODE DE MEXICO S.A. DE C.V.  =Amerinode Brazil /Amerinode Ecuador/Amerinode South America",
  "NCS Global Services LLC/NCS West",
  "On Queue Computer Inc",
  "Index Computer Remarketing",
  "LSI Technology Remarketing (LSI) (EZZELL ENTERPRISE, INC)",
  "Somet Integration Ltd",
  "I mac and more",
  "InterNative Supply",
  "Nidam Communication = Chip PC Inc.",
  "For Your Workplace LTD  Pine Supplies BV Pine Projects BV Pine Group BV Pine Services BV Telecom Supplier Deutschland GmbH telecomhunter telecomsupplier",
  "ScanFocus",
  "WDIXITAL SPAIN, SLU",
  "MCR-Austria / Mobile Computer Repair",
  "Arbitech, LLC(BecTech Global)",
  "Comstex GmbH & Co. KG",
/// 杨少棠
  "Data Capture Solutions (Legacy Technology Services)",
  "Mileservices",
  "Rhino technology",
  "Shop4Tele Inc (Techzone Direct)",
  "Sotel Systems",
  "Technology Recovery Group/TRG Global  (TRG) (Barcode Repair)",
  "SCSISTUFF, LLC",
  "BE NETWORKS",
  "Carritech Limited (Carritech Telecomunicaciones S.L.U)",
  "RAA TECHNOLOGY SOLUTIONS LTD  RAA IT Solution",
  "IMN",
  "wizzardwerks",
  "Taldor Group (Taldor computer systems (1986) Ltd)",
  "Sterry Telecom",
  "Network Craze Technologies",
  "TDW (Technology Distribution Worldwide LLC）",
  "1st Tier Technology",
  "Advanced Computer Systems LLC(ACS)",
  "G&S Communications and Technical Services",
  "Sterling Mobile Services, Inc",
/// 陆春洪
  "Astrocom Systems((VCF) )",
  "BT Systems Inc",
  "Carlton Technologies, Levata (Barcodes, Inc, BarcodesInc)",
  "Flagship Technologies Inc.",
  "ICS Europe Ltd (INTEGRATED COMPONENT SOURCE EU LTD)",
  "Impact Computers",
  "Kimbrer Computer ApS (Renewtech)",
  "Max ICT B.V.",
  "Missdata Di Romano Scilla （MISSDATA SRLS）",
  "PCM Leasing Corp",
  "Quazo Systems",
  "Telecoms Traders Ltd",
  "Telefone Resources (UK) Ltd",
  "TKO Electronics, Inc. (ExpressPoint Technology)",
  "WestWorld Telecom Corporation",
  "Billigteknik Sweden AB",
  "RED EAGLE IT Distribution GmbH",
  "D&S Communications, Inc.",
  "Tradenet Technology",
  "Integrity Global Solutions (IGS)",
  "Retail Tech Inc",
  "Combro Technology Limited",
  "Data Networks International (Data Networks Int’l)",
  "M&M",
  "PULSEINFORMATICA",
  "Iris Conex Ltd",
  "Bitcare - Tecnologias de Informacao, SA",
  "Anlauf Hardware GmbH",
  "South Supply TN",
  "Cypress Technology, Inc(J+J Nationwide enterprises)",
  "P3 Systems",
  "ScandicTech AS",
  "Barcode Supply (Barcode Buyback)",
  "ReCon-IT GmbH",
  "Matrizmultipla - Unipessoal LDA",
  "Infocus ID Ltd",
  "JANS-it",
/// 卢秋婷
  "AirWay Technologies, INC",
  "Evernex (aka IB REMARKETING, Technogroup IT-Service Sp. z o.o )",
  "Fala Limited (Barcode Trade)",
  "NAS IT Solutions Ltd",
  "PICS Telecom (PICS Telecom International Ltd. ) (PICS Telecom International Asia Ltd. )",
  "TXO Systems (MMX Communications)",
  "Diversitec",
  "SunCoast Communication",
  "BrainBridge Outsourcing Services Pvt Ltd",
  "AJ Networx",
  "Revo Distribution Limited",
/// 余安
  "ADE-Vertriebs GmbH",
  "Codeo (Codeo Iberia)",
  "Inrego AB (Inrego Global AB)",
  "Sell Phone System (Clarion Communication Systems Ltd)",
  "Shields Environmental Ltd",
  "ComSources, LLC",
  "RuA Bademli GbR",
  "POS Solutions s.r.o.",
  "Master for computer (Luxury Store)",
  "Global United LLP",
  "Astringo Commodities Ltd (Rugged.tech)",
  "Z3-IT, Onken IHB UG(Stahlmann & Sachs GmbH) BM Networks, Blue Mountain Networks LLC (Platinum Networks, Inc.)  Telecom Discount B.V",
  "Codinfos",
  "Circular IT",
  "Telecom Easy Scandinavia AB",
  "Estunt BV",
  "SPLUS TECHNOLOGIES LLC",
  "Hardware You SLU Hardware You & Cloud",
  "PBXports Ltd",
  "Optimum Routing Machine Systems FZCO（ORM Systems）",
  "Tekeurope UK Ltd",
/// 莫月慧
  "Ameta Computer ApS",
  "Dealstunter",
  "Global Computer Sales",
  "JP Computer Trading",
  "MS Development (Hardware Direct)",
  "Open Market Trading, LLC",
  "Origin Micro, Inc",
  "Preyveng Trading Ltd",
  "Four Nordic",
  "okpos chile spa (Comercializadora e importadora Renmar limitada)",
  "Frogtech",
  "Andrej Lamovsek",
  "Caique goncalves",
  "BayInfoNet Corp (BayInfoTech Corp)",
  "G5 Network（G5 Network Group）",
  "Mekhrob NAVRUZOV",
  "Stack Systems KFT(Stack Systems Trade FZ LLC)",
  "Alpha-Dox（Alpha-Dox B.V.）",
  "C2 Digital Solutions Ltd",
  "Ballet jean marc",
  "Feda Trading BV",
  "Tech Network Supply LLC(Yellow Networks LLC)",
  "Otisco valley telcom",
  "DMS Technology, Inc. (DMS Technologies Inc)",
  "Powerful system",
  "aam muharam",
  "Glocean INC (Synotex INC, PAX Solutions)",
  "ermenegildo arrivillaga",
  "DiGiworks Co., Ltd(CharonTech Co., Ltd) KERBEROS CO.",
  "Jerry Howard",
  "cheolhwa lee （joosung）",
  "Overseas Technology Center Pte LTd",
/// 安雅琼
  "DSM Distribution",
  "Euro IT Solution LTD (Tier1 Data Systems)",
  "MTS IT Systems",
  "PDAserwis (PDAgroup , 24barcode)",
  "Pecunia24",
  "REVOLVING NETWORKS",
  "RL Networks B.V. (Maxicom IT Distribution B.V.) CITg Netherlands B.V.",
  "The Best Part, Inc.",
  "Trio Supply Chain Solutions, LLC",
  "TSP SYSTEM Co.,Ltd",
  "Surplus Computer Spares (SCS)",
  "True Technologies LLC",
  "Cobra Tech Solutions LLC",
  "ETB Technologies Ltd",
  "Four IT Group(D-TWO B.V.)",
  "TVDL Computers",
  "Technoverse Business Solutions",
  "MAG Traders Ltd",
/// 单倩倩
  "ADCbit B.V.",
  "Codelogic",
  "Comptest Polska Sp z o. o. (COMPTEST GROUP SP Z O.O.)",
  "CUADRANT ( Netmode, NETGenetics, Platform Management LLC, Accela Networks , Volantra Networks)",
  "Cyberpulse Computing LTD",
  "Cybertrading GmbH (IT Market, IT-Market)",
  "FEATURECOM INC. (Lean Supply Solutions, Emerge IP)",
  "Macondo Networks",
  "MetrolineDirect (Metroline Inc, Phone Installers)",
  "Network ISE Digital Technologies LTD (NETWORKISE CLOUD TECHNOLOGIES L.L.C)",
  "reflex.sys",
  "Resource Point of Sale",
  "SPC International Ltd (Rico Logistics Ltd) (TVS Supply Chain Solutions, TVSSCS)",
  "Tawakkal Infotech LLC (LinkServe) LINK SUPPORT FOR INDUSTRIAL SERVICES EST (Linkserve)",
  "Toga Informática",
  "Washburn Computer Group",
  "Simpatico Network srl",
  "IT-Planet GmbH",
  "Ghekko Limited (Ghekko Networks Inc. , A1 Teletronics, Inc.)",
  "Macrefresh Ltd",
  "NKS Group Sp. z o. o.",
  "Inforsight Ltd Inforsight Limited",
  "MinutioConsultingGmbH (Minutio Consulting GmbH)",
  "GRUPO DIGALCO SL",
  "Lorimax 2000 Impex srl (SC LORIMAX 2000 IMPEX SRL)",
  "Thinkgreen SARL （SARL THINKGREEN - INFO26200）",
  "Illinois Wholesale Cash Register (IW Technologies)",
  "IT WEST STORE （IT WEST STORE LLC-FZ）",
  "Strada Networks, LLC (DCS Global B.V. , Data Center Solutions)",
  "RECYCLY.TECH LTD",
  "Technimove Recycles",
  "Group24 AG",
  "Ecoele UG",
  "Good PC OU（Good PC OÜ，Wise Europe S.A，Good Choice）",
  "Connect IT (Connect IT B.V.) （Info . Connect IT）",
  "Advance Vendor Access",
  "HCO Group Limited (Re-Macs)",
  "Tellus Remarketing ApS (Tier1 Asset A/S) Tellusrem)",
  "Refurb-UK",
/// 文明
  "A.B. Distributing, Inc (B3E LLC, Sachem, LLC)",
  "Advanced Technologies International LLC",
  "Control House International",
  "Micro Solution Web LCC",
  "OutletClick.Com (Insis d.o.o.)",
  "PT Refurb Unipessoal Lda / RFI UNIP LDA",
  "SabrePC.com/Exxact Corporation",
  "Propersearch Ltd",
  "Sahar gul computer Tr llc",
  "Arzotec ApS",
  "Techsource / Techsource Global (TSGlobal.io)",
  "Tecnoban Inc",
  "Bravo Communication, Global net source(GNS)/Singular Grape Inc",
  "TecBox",
  "Pexbo (RED AND WHITE NETWORK LLC) Copy Solutions SRL",
  "Hillside Electronics Corporation",
  "MAS Integrated Systems(MAS)Ceremony LTD",
  "Nanosoft Corporation Limited",
  "EONETIX Information Technology",
  "Media & Communications Ltd (Best4Systems)",
  "Oredax",
  "A-tech network",
  "Greyhound Networks Ltd",
  "zekers",
  "Maker IT",
  "Today Tech",
  "Scottish Data Systems",
  "Tazabitz Computer Consulting Inc",
  "THORPETO INC",
  "Continental Computers",
  "Get IT New Inc",
  "IT4Trade",
  "Paxel Technologies",
  "NewAge Technology Solutions, LLC",
  "D&B Distributors Ltd",
  "Zayntek (Fornida)",
/// 陈珊珊
  "Communications & Data, Inc（C&D Associates, Inc./C&D Communications,Inc）",
  "Computer-wereld",
  "Econocom Factory  sofigroupe (Econocom SA, SMAAART, Jiliti)",
  "Ecoportatil.es (PORTATILECO ESPAÑA S.L)",
  "FLEXIT B.V. (Xeptor B.V. , Flex IT Distribution, Infotheek Groep NV, Infotheek Holding B.V.)",
  "furbify s.r.o.",
  "IT Gigant ( RCW) (Retail Computer Warehouse)",
  "KONSER OHG (notebookgalerie.de)",
  "Advance Services & Solutions Ltd",
  "PC Renewed Ltd",
  "Procurri Procurri Europe Ltd (Procurri Europe Parts Sales), Procurri Asia Pacific, Procurri Europe Lifecycle Services,  Procurri USA,  Procurri GmbH,  Procurri Singapore Pte Ltd, Procurri Malaysia Sdn, Great Windmill c/o Procurri",
  "Pure IT Recycling",
  "Paragon Communications Inc(PARAGON, NTS DIRECT) Telesource Services, Inc",
  "Technimax s.r.o.",
  "technocycle GmbH",
  "TelQuest International",
  "Thats IT",
  "Phoenix Tech s.r.l. (Hi-Tech Outlet)",
  "Brugtecomputere.dk (Ecommunication A/S)",
  "Interbolt.eu Kft",
  "Notebookservice SRL (keyboardprint, AKCENTA CZ A.S. )",
  "Smart Dragon SL",
  "Memtech sp. z o.o. sp. kom.",
  "Apronet - IT Distribution (APRONET UNIPESSOAL LDA)",
  "preiswerte-IT.de GmbH",
  "Foxway OU Foxway UK Foxway A/S Foxway Distribution Dansk Computer Center A/S (DCC) ExcessIT Middle East Electronics Trading L.L.C",
  "RQ Communications (Retrotel, Inc)",
  "GSD Remarketing GmbH & Co. KG (gsd.eu) RS ITL Verwaltungs GmbH",
  "Advanced Computer Trading (actsl.com)",
  "My IT Street (MIS)",
  "Bell IT GmbH (Bell IT Inc.)",
  "Arcas Technology Inc",
  "BUILD369 doo",
  "Teksavers Inc Teksavers (Singapore)",
  "NexGen Technology LLC (Hardware Storm)",
  "refublic",
  "CARRIER SERVICES GROUP （CSG）",
  "NCOM SRL",
  "Direct Hardware Supply (DHS)",
  "A2C Services Ltd/ Circular Computing",
  "Digoo IT Distribution",
  "Datamax System Solutions Datamax Services Inc.",
  "Cykero Cykero GMBH Cykero SAS",
  "Atoutek SAS",
  "Interlink Computer Shop (Interlink Group srl)",
  "Marseus Computer Kft",
  "KT-Trading OY",
  "Q Products BV",
  "AlfaNet S.A. (AlfaNet SYSTIMATA) ALFANET SISTIMATA PLIROFORIKIS S.A",
  "Renew-IT Solutions (GVS Consulting) (GVS Consulting COMMV)",
/// 陶丽珍
  "All Birotic Devices",
  "Carlex Ltd",
  "Ecodair ea Paca",
  "ESI Technologies Inc",
  "inComputer s.r.o",
  "Northland Systems",
  "ReuseIT Sweden AB",
  "Serverfi Ltd",
  "Vladimir Chumakov / Hells Dells Chumakov / Aranovsky GbR",
  "MTJ Electronics",
  "BudgetTrading",
  "LM Eco Production",
  "Backslash Vertriebs GmbH",
  "COMPOSITE NETWORK",
  "Go Communications Systems",
  "Interbyte Pty Ltd",
  "Datamarked Aps（ITFIX Mariusz Fiertek）",
  "Notebook-Pro NPH GmbH",
  "Vooruit",
/// 张连军
  "Blue Point Voice and Data",
  "CBA Computer Broker AG",
  "Connectzone /Technacable",
  "Flux IT Hardware Ltd",
  "Micropeer Solutions",
  "Neo Data Technologies LLC",
  "SPC - Sales & Purchasing Consultancy",
  "Vodanet Systems LLC (Wisewired) Euronet Systems GmbH",
  "SBS Trading LTD",
  "Mosaic Technology Corporation",
  "RADAN TRADE",
  "ESphere Network GmbH",
  "Vibrant Technologies, Inc. (Techworks)",
  "FORSERVER ( Universal Technology & Logistics INC , ServerMark )",
  "MULTIPLE NETWORKS LTD",
  "T.I Digital Solution LTD",
  "PC warehouse",
  "Maraelite Kft",
  "Nexus Node Systems LTD",
  "FTNC Ltd (Forward Thinking Network Consultancy Ltd)",
  "IP Supply Pty Ltd",
  "MF Communications Limited",
  "TXC Technologies LLC",
  "Bitboard OÜ (LLC)",
/// 赖腾龙
  "Re-certify",
  "European Network Services SARL (ENS)",
  "tacladders it",
  "Menke IT GmbH",
  "Docwizz SRL",
  "NTAST",


  //有误的数据
  "Rhino Technology Group, Inc",
  "MF Communications UK Ltd",
  "TEKEUROPE UK",
  "Renewtech DK fka. Kimbrer Computer ApS",
  "Tekeurope UK Limited - Devon",
  "ORM Systems LLC USA",
  "Codinfos S.L.",

  //干净的数据
  "IT Product Supply LTD",
  "Bizcom Europe Sp. z o.o.",
  "Elevate Networks",
  "SKTes France, SKtes Spain",
  "Computer Data Source",
  "Mobilos Single Member P.C. | VMS",
  "Jet Computer",
  "FORMAX",
  "Kortek Ltd.",
  "IT Refresh",
  "Aeon Micro, Inc.",
  

  //新增别名数据 干净数据里的
  "VOTERONIX LTD",
  "VMS Ltd",

  
  //没找到的公司
  "Andeltech Electronics, GIGAHARDWARE",

  //中国公司
  "Acorn Tech Service Limited",
  "Quiksol International HK PTE limiteds",
  "Highsource Technology Co.Ltd",
  "CENTURY FUGUANG CO., LTD.",
  "Grandtec Industrial (Hongkong) Co., Ltd",
  "Shengyue Technology Co., Ltd",
  "Convey Telecom Limited",
  "Top IT Service Limited,fka Uniworld",
  "DECHO Network Technology LTD",
  "Joy Online Network Limited",
  "Coopak Networks",
  "CAICHIPS PET LTD",
  "Topstar Technology Industrial Co., Limited",
  

  //被拉黑
  "Memory Clearance",
  "Tacladders IT Solutions Private Limited",

  //死忠粉
  "CEC",


  ///不从欧洲以外买
  "Datek Solutions Ltd",
  
];
